# Generated by Django 4.0.4 on 2022-05-03 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eshop.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_eshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), eshop.core.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), eshop.core.validators.validate_only_letters])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
