# Generated by Django 4.0.4 on 2022-05-03 09:27

import django.core.validators
from django.db import migrations, models
import eshop.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(3), eshop.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(3), eshop.core.validators.validate_only_letters]),
        ),
    ]
