# Generated by Django 4.0.4 on 2022-05-04 12:47

import django.core.validators
from django.db import migrations, models
import eshop.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default=2018, max_length=9, validators=[django.core.validators.MinLengthValidator(8), eshop.core.validators.validate_only_numbers]),
            preserve_default=False,
        ),
    ]
