# Generated by Django 4.0.4 on 2022-05-05 13:59

import django.core.validators
from django.db import migrations, models
import eshop.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), eshop.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), eshop.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(8), eshop.core.validators.validate_only_numbers]),
        ),
    ]
